import baseOne from "@/assets/mars.1.jpeg.asset.json";
import baseTwo from "@/assets/mars.3.jpeg.asset.json";
import baseThree from "@/assets/mars.12.jpeg.asset.json";
import baseFour from "@/assets/mars.123.jpeg.asset.json";
import baseFive from "@/assets/mars.habit.jpeg.asset.json";
import baseSix from "@/assets/mars.habitat.jpeg.asset.json";

export const habitats = [
  {
    id: "aurora",
    name: "Aurora Research Post",
    region: "Arcadia Planitia",
    lat: 0.25,
    lon: -0.8,
    image: baseOne.url,
    description: "A compact polar-science post positioned above shallow ice deposits. Its buried sleeping cells connect directly to a chemistry lab and autonomous drilling bay.",
    systems: ["Ice extraction", "Subsurface bunks", "Geochemistry lab", "Storm radar"],
    capacity: "8 crew",
    score: 89,
    solar: "612 W/m²",
    ice: "97%",
    stability: "84%",
    metrics: [92, 68, 86, 91, 84, 79],
    conditions: ["Confirmed", "Seasonal", "Stable"],
  },
  {
    id: "kepler",
    name: "Kepler Landing Hub",
    region: "Elysium Planitia",
    lat: 0.36,
    lon: 0.1,
    image: baseTwo.url,
    description: "A logistics-focused landing hub on young volcanic plains. Separated pads, fuel processing, and rapid rover servicing support missions moving across the eastern hemisphere.",
    systems: ["Methane refinery", "Landing control", "Rover service", "Cargo robotics"],
    capacity: "18 crew",
    score: 86,
    solar: "735 W/m²",
    ice: "61%",
    stability: "93%",
    metrics: [61, 91, 79, 72, 95, 94],
    conditions: ["Probable", "Excellent", "Very stable"],
  },
  {
    id: "delta",
    name: "Delta Science Haven",
    region: "Jezero Crater",
    lat: -0.13,
    lon: 0.78,
    image: baseThree.url,
    description: "A field station beside the ancient river delta, optimized for sample curation and astrobiology. Sterile laboratories isolate returned cores from the residential ring.",
    systems: ["Sample vault", "Clean laboratory", "Algae bioreactor", "Drone hangar"],
    capacity: "14 crew",
    score: 92,
    solar: "704 W/m²",
    ice: "82%",
    stability: "79%",
    metrics: [82, 87, 74, 78, 76, 91],
    conditions: ["Likely", "Strong", "Moderate"],
  },
  {
    id: "mariner",
    name: "Mariner Canyon Base",
    region: "Valles Marineris",
    lat: -0.38,
    lon: -0.32,
    image: baseFour.url,
    description: "A cliff-anchored geology base shielded by canyon walls. Pressurized lifts link the valley floor to instrument galleries carved into layered rock.",
    systems: ["Rock shielding", "Pressure lifts", "Seismic array", "Cliff observatory"],
    capacity: "24 crew",
    score: 84,
    solar: "548 W/m²",
    ice: "58%",
    stability: "71%",
    metrics: [58, 62, 88, 95, 66, 73],
    conditions: ["Uncertain", "Limited", "Complex"],
  },
  {
    id: "helios",
    name: "Helios Energy Camp",
    region: "Solis Planum",
    lat: 0.02,
    lon: 1.28,
    image: baseFive.url,
    description: "An equatorial power station built around a wide field of dust-shedding solar mirrors. The camp stores surplus energy for nearby expeditions and orbital relays.",
    systems: ["Solar concentrators", "Battery vault", "Grid control", "Dust clearing"],
    capacity: "12 crew",
    score: 88,
    solar: "781 W/m²",
    ice: "43%",
    stability: "90%",
    metrics: [43, 98, 83, 69, 91, 88],
    conditions: ["Sparse", "Exceptional", "Stable"],
  },
  {
    id: "northstar",
    name: "Northstar Ice Station",
    region: "Utopia Planitia",
    lat: -0.56,
    lon: 0.37,
    image: baseSix.url,
    description: "A cold-climate water plant where thermal drills harvest buried ice. Redundant tunnels connect processing, storage, and crew modules beneath insulated berms.",
    systems: ["Thermal drills", "Water refinery", "Heat recovery", "Buried tunnels"],
    capacity: "20 crew",
    score: 90,
    solar: "566 W/m²",
    ice: "99%",
    stability: "88%",
    metrics: [99, 57, 91, 93, 87, 81],
    conditions: ["Abundant", "Seasonal", "Stable"],
  },
  {
    id: "horizon-city",
    name: "Horizon City",
    region: "Isidis Planitia",
    lat: 0.19,
    lon: 2.28,
    image: baseTwo.url,
    description: "A large civic settlement arranged around a pressurized central commons. Residential districts, schools, clinics, and fabrication halls support permanent family life.",
    systems: ["Civic commons", "Regional hospital", "Industrial fabrication", "Transit loop"],
    capacity: "180 residents",
    score: 94,
    solar: "716 W/m²",
    ice: "87%",
    stability: "92%",
    metrics: [87, 89, 88, 86, 93, 96],
    conditions: ["High confidence", "Excellent", "Very stable"],
  },
  {
    id: "olympus",
    name: "Olympus Grand Habitat",
    region: "Olympus Mons",
    lat: 0.49,
    lon: -1.72,
    image: baseFour.url,
    description: "A high-altitude arcology spanning multiple pressure sectors. Its observatories, vertical farms, and manufacturing decks form a self-reliant mountain community.",
    systems: ["Vertical agriculture", "Pressure sectors", "Orbital observatory", "Ceramic works"],
    capacity: "260 residents",
    score: 82,
    solar: "806 W/m²",
    ice: "38%",
    stability: "86%",
    metrics: [38, 99, 76, 83, 85, 89],
    conditions: ["Imported", "Exceptional", "Stable"],
  },
  {
    id: "noctis",
    name: "Noctis Underground",
    region: "Noctis Labyrinthus",
    lat: -0.29,
    lon: -2.52,
    image: baseOne.url,
    description: "A large underground settlement occupying reinforced lava tubes. Natural shielding protects residential gardens, machine shops, and long-term archives from radiation.",
    systems: ["Lava-tube shielding", "Hydroponic terraces", "Archive vault", "Geothermal loop"],
    capacity: "320 residents",
    score: 91,
    solar: "492 W/m²",
    ice: "73%",
    stability: "95%",
    metrics: [73, 54, 96, 99, 94, 78],
    conditions: ["Accessible", "Supplemental", "Exceptional"],
  },
  {
    id: "gale",
    name: "Gale Crater Complex",
    region: "Aeolis Mons",
    lat: -0.09,
    lon: 2.92,
    image: baseSix.url,
    description: "A broad research and education complex combining surface domes with excavated laboratories. It supports universities, rover fleets, and a regional emergency center.",
    systems: ["University labs", "Rover fleet", "Emergency center", "Closed-loop farms"],
    capacity: "210 residents",
    score: 87,
    solar: "683 W/m²",
    ice: "69%",
    stability: "83%",
    metrics: [69, 84, 81, 87, 82, 93],
    conditions: ["Probable", "Favorable", "Good"],
  },
] as const;

export type Habitat = (typeof habitats)[number];